### ISSUE TITLE
Fix error 'Segmentation fault (core dumped)'.

### ISSUE THREAD

**Issue by adriaan1539** [adriaan1539/Bank_data_import#3]
The line 'Rule shellinNameRule(shellInNameFunction);' in 'main.cpp' causes the error 'Segmentation fault (core dumped)' and I don't know why.

https://github.com/adriaan1539/Bank_data_import/blob/4315be4ae633fea44535e1ed71228ae71e10e5dd/main.cpp#L45

**Comment by tseidler** [comment]
What is a "shell in name"?

**Comment by adriaan1539** [comment]
Fixed the error in commit e9d3661667f7b67e22a465d53ff16dbefe860bce. I used 'push_back' on an object of the wrong type.
